{{- if and .Values.openldap.enabled (.Values.openldap.serviceAccount.create | default true) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-openldap" (include "mas-iam-stack.fullname" .)) .Values.openldap.serviceAccount.name }}
  labels:
    {{- include "mas-iam-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: openldap
{{- end }}
