{{- if and .Values.keycloak.realmImport.enabled .Values.keycloak.realmImport.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mas-iam-stack.fullname" . }}-realm-import
  labels:
    {{- include "mas-iam-stack.labels" . | nindent 4 }}
data:
{{- range $file := .Values.keycloak.realmImport.files }}
  {{- $target := default (base $file.file) $file.target -}}
  {{- printf "%s: |" $target | nindent 2 }}
{{ $.Files.Get $file.file | indent 4 }}
{{- end }}
{{- end }}
